#!/bin/bash
command=$1
key=$2
value=$3
bash_file="$HOME/.bashrc"

function search(){
	query=$1
	printenv | grep $query
}

function set(){
	export $key=$value
	update $key
	echo "Run the following line"
	echo "---------------------------------------"
	echo "> source $bash_file"
	echo "---------------------------------------"
	echo "To update the changes made."	
}

function get(){
	printenv $key
}

function update(){
	variable=$1
	old=$(cat $bash_file | grep "export $variable")
	new="export $variable="$(printenv $variable)
	
	if [ "$old" ]; then
		$(sed -i .benv.backup "s/$old/$new/g" $bash_file)
	else
		echo $new >> $bash_file
	fi
}

function main(){
	$command
}
main