#!/bin/bash
command=$1
value=$2
bash_file="test.txt"

function search(){
	query=$1
	printenv | grep $query
}

function update(){
	variable=$1
	old=$(cat $bash_file | grep "export $variable")
	new="export $variable="$(printenv $variable)
	$(sed -i .benv.backup "s/$old/$new/g" $bash_file)
}

function main(){
	$command $value
}
main